apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-nginx
  namespace: ai-lab
spec:
  replicas: 1
  progressDeadlineSeconds: 20
  selector:
    matchLabels: {app: broken-nginx}
  template:
    metadata:
      labels: {app: broken-nginx}
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
